version: '3'
services:
  app: &app_base
    environment:
      TZ: Asia/Tokyo
    build: .
    command: ["bundle", "exec", "ruby", "app.rb"]
    depends_on:
      - db
    ports:
      - "4567:4567"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
  db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/data/goblin_db:/var/lib/mysql
volumes:
  bundle_cache: